version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    hostname: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mrango
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"

  app:
    build:
      context: ./src
    container_name: app
    hostname: app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/marango
    command: sh -c "chmod 777 -R  /var/www/html/marango/assets && apache2-foreground"
    depends_on:
      mysql:
        condition: service_healthy