version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Orchestra
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"

  php:
    build:
      context: ./PHPServerConfig
      dockerfile: Dockerfile
    container_name: php-server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy